config/routes.rb
DoSomthIn::Application.routes.draw do

  devise_for :user

  root :to => 'issues#index'

  resources :application

  get 'issues/:issue_id/upvote' => 'issues#upvote', :as => :issue_upvote
  get 'issues/:issue_id/downvote' => 'issues#downvote', :as => :issue_downvote

  resources :issues

  get 'user/dashboard' => 'users#dashboard', :as => :dashboard

  resources :comments

end

app/models/issue.rb
class Issue < ActiveRecord::Base

	validates_presence_of :title, :description, :goal
	belongs_to :user
	has_many :votes
	has_many :comments

	def self.Trending
		issues = Issue.all
		#binding.pry
		valued = issues.map {|i| [i, i.trending_heuristic]}
		valued.sort! {|a, b| b[1] <=> a[1]}
		return valued.map{|i| i[0]}
	end

  def self.New
    return Issue.order(:created_at)
  end

  def self.Top
    return Issue.order(:votes_count)
  end

  def trending_heuristic
    result = 0.0
    votes.each do |v| 
     diff = TimeDifference.between(v.created_at, Time.now).in_minutes
     result += 1.0/diff
   end

   return result
  end

  def owner_name
    "#{user.first_name} #{user.last_name}"
  end

  def up_votes
    return votes.where(vote_type:Vote::TYPES[:up_vote])
  end

  def up_vote_count
    return up_votes.count
  end

  def down_votes
    return votes.where(vote_type:Vote::TYPES[:down_vote])
  end

  def down_vote_count
    return down_votes.count
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /issues/1/upvote
  def upvote
    @issue = Issue.find(params[:id])
    @issue.votes.create
    redirect_to(issues_path)
  end

  # GET /issues/1/downvote
  def downvote
    @issue = Issue.find(params[:id])
    @issue = Issue.votes.create
    redirect_to(issues_path)
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :ok }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper

  def up_vote_percentage(issue)
    return issue.votes_count > 0 ? (issue.up_vote_count.to_f / issue.votes_count.to_f)*100 : 0
  end

  def down_vote_percentage(issue)
    return issue.votes_count > 0 ? (issue.down_vote_count.to_f / issue.votes_count.to_f)*100 : 0
  end

end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, User.all, :id, :first_name %><br />
  </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :goal %><br />
    <%= f.text_area :goal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="navbar navbar-default">

      <div class="navbar-header navbar-brand">Issues</div>

      <%= link_to new_issue_path, :class => 'btn btn-success', :id => 'new-issue-nav-button' do %>
        <h3><span class="glyphicon glyphicon-plus"></span> New Issue</h3>
      <% end %>

      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'New', issues_path %></li>
        <li><%= link_to 'Trending', issues_path, order: 'Trending' %></li>
        <li><%= link_to 'Top', issues_path, order: 'Top' %></li>
      </ul>

    </div>

  </div>
</div>

<br />


<% @issues.each do |issue| %>
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <div class="row">
<!--         <div class="col-xs-3 col-md-3 text-center">
          <img src="http://bootsnipp.com/apple-touch-icon-114x114-precomposed.png" alt="bootsnipp"
          class="img-rounded img-responsive" />
        </div> -->
        <div class="col-md-12 section-box">

          <div class="h2"><%= link_to issue.title, issue %>
          <small class="issue-meta pull-right">By: <%= issue.owner_name %> Posted: <%= issue.created_at %></small>
          </div>
          
          <p class="issue-excerpt text-primary"><b>Goal: </b><%= truncate(issue.goal, length:100) %></p>
          <p class="issue-excerpt"><%= truncate(issue.description, length:250) { link_to "More", issue } %></p>
          
          <hr />

          <div class="deep-well">
            <div class="rating-desc">

              <div class="col-md-6">

                <h5>Yay Votes</h5>

                <div class="col-md-9"><div class="progress"><% up_percentage = up_vote_percentage(issue) %>
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= up_percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= up_percentage %>%">
                    <span class="sr-only"><%= up_percentage %>% Yay Votes</span>
                  </div>
                </div></div>

                <div class="col-md-3">
                  <%= up_percentage %>% Yay <small>(<%= issue.up_vote_count %>)</small>
                </div>

              </div>

              <div class="col-md-6">

                <h5>Nay Votes</h5>

                <div class="col-md-9"><div class="progress"><% down_percentage = down_vote_percentage(issue) %>
                  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<%= down_percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= down_percentage %>%">
                    <span class="sr-only"><%= down_percentage %>% Nay Votes</span>
                  </div>
                </div></div>

                <div class="col-md-3">
                  <%= down_percentage %>% Nay <small>(<%= issue.down_vote_count %>)</small>
                </div>

              </div>
            </div>
            
            <div class="clearfix"></div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="navbar navbar-default">

      <div class="navbar-header navbar-brand"><%= link_to issues_path do %><span class="glyphicon glyphicon-chevron-left"></span> Back to Issues<% end %></div>

      <% if user_signed_in? %>
      	<div class="ui-group-buttons pull-right">
			<%= link_to issue_upvote_path, :class => 'btn btn-success', :id => 'upvote-button', :issue_id => @issue.id do %><span class="glyphicon glyphicon-thumbs-up"> Yay</span><% end %>
			<div class="or"></div>
			<%= link_to issue_downvote_path, :class => 'btn btn-success', :id => 'downvote-button', :issue_id => @issue.id do %><span class="glyphicon glyphicon-thumbs-down"> Nay</span><% end %>
		</div>
	<% end %>

    </div>

  </div>
</div>

<br />


<div class="h2"><%= @issue.title%>
	<small class="issue-meta pull-right">By: <%= @issue.owner_name %> Posted: <%= @issue.created_at %></small>
</div>

<hr />

  <b>Description:</b>
  <%= @issue.description %>
</p>

<p>
  <b>Goal:</b>
  <%= @issue.goal %>
</p>

<p>
  <b>Comments:</b>
<% if user_signed_in? %>
  <%= text.area :comment %>
 <% end %>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>