config/routes.rb
DoSomthIn::Application.routes.draw do

  devise_for :user

  root :to => 'issues#index'

  resources :application

  get 'issues/:issue_id/upvote' => 'issues#upvote', :as => :issue_upvote
  get 'issues/:issue_id/downvote' => 'issues#downvote', :as => :issue_downvote

  resources :issues

  get 'user/dashboard' => 'users#dashboard', :as => :dashboard

  resources :comments

end

app/controllers/application_controller.rb
# =Temporary Controller
# ==This is mostly for Lab #5

# ==To-Do for this controller
# 1. Finish this rdoc tutorial/lab thingee.
# 2. Show it to the TA for the lab.
# 3. Delete this controller.
# 4. Never think about it again!

class ApplicationController < ActionController::Base

	layout 'application'


	def index
		render 'issues/index'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class_type(name)

    # binding.pry

    danger_names = ['alert', :alert]

    if danger_names.include?(name)
      return 'alert-danger'
    else
      return 'alert-warning'
    end

  end
  
end

app/views/application/_bottom.html.erb
<footer class="footer">

</footer>

app/views/application/_top.html.erb
<header class="header">

	<ul class="nav nav-pills pull-right">

		<% if user_signed_in? %>
			<li><%= link_to "New issue", new_issue_path %><br />
		<% end %>
		<li class="active"><%= link_to "Home", application_index_path %></li>
		<% if user_signed_in? %>
			<li><%= link_to "Sign out", destroy_user_session_path %><br />
			<li><%= link_to "Dashboard", dashboard_path %><br /> 
		<% else %>
			<li><%= link_to "Sign in", new_session_path(:user) %><br />
			<li><%= link_to "Register", new_registration_path(:user) %><br />
		<% end %>
		<li><a href="#">Contact</a></li>
	</ul>
	<h3 class="text-muted">Do Somthin!</h3>
</header>

app/views/application/index.html.erb
<div class="jumbotron">
	<h1>Jumbotron heading</h1>
	<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
	<p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
</div>

<div class="row marketing">
	<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>

	<div class="col-lg-6">
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>
</div>